app = "portfolio-terminal"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8000"
  REDIS_URL = ""  # Will be populated during deployment

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[[services.ports]]
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "get"
  path = "/healthz"
  protocol = "http"
  restart_limit = 0
  timeout = "2s"