apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - backend
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: backend
        image: aouichou.azurecr.io/backend:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app/media
          name: media-volume
        envFrom:
        - secretRef:
            name: database-credentials
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc
