# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: init-media
        image: aouichou.azurecr.io/backend:latest
        command:
          - sh
          - -c
          - |
            if [ -z "$(ls -A /app/media)" ]; then
              cp -R /app/prepopulated_media/* /app/media/;
            fi
        volumeMounts:
          - name: media-volume
            mountPath: /app/media
      containers:
      - name: backend
        image: aouichou.azurecr.io/backend:latest
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: /app/media
            name: media-volume
        envFrom:
          - secretRef:
              name: database-credentials
        env:
          - name: AZURE_EMAIL_KEY
            valueFrom:
              secretKeyRef:
                name: email-config
                key: AZURE_EMAIL_KEY
          - name: CONTACT_RECIPIENT
            valueFrom:
              secretKeyRef:
                name: email-config
                key: CONTACT_RECIPIENT
          - name: AZURE_EMAIL_USER
            valueFrom:
              secretKeyRef:
                name: email-config
                key: AZURE_EMAIL_USER
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc