apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: init-media
        image: busybox
        command:
          - sh
          - -c
          - |
            # Prepopulate /app/media only if it is empty.
            if [ -z "$(ls -A /app/media)" ]; then
              cp -R /app/prepopulated_media/* /app/media/;
            fi
        volumeMounts:
          - name: media-volume
            mountPath: /app/media
      containers:
      - name: backend
        image: aouichou.azurecr.io/backend:latest
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: /app/media
            name: media-volume
        envFrom:
          - secretRef:
              name: database-credentials
          - secretRef:
              name: django-secrets
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc