apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NEXT_PUBLIC_API_URL: "https://aouichou.me/api"
  NEXT_PUBLIC_MEDIA_URL: "/media"
  # Add other frontend environment variables here