apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
spec:
  accessModes:
    - ReadWriteMany  # Ensure this matches the initial creation
  storageClassName: azurefile  # Example: Azure Files storage class
  resources:
    requests:
      storage: 5Gi 