# Generated by Django 5.0.11 on 2025-02-28 16:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='ContactSubmission',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=100)),
				('email', models.EmailField(max_length=254)),
				('message', models.TextField()),
				('created_at', models.DateTimeField(auto_now_add=True)),
			],
		),
		migrations.CreateModel(
			name='Project',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('title', models.CharField(max_length=200)),
				('slug', models.SlugField(blank=True, unique=True)),
				('readme', models.TextField(blank=True)),
				('description', models.TextField()),
				('tech_stack', models.JSONField(default=list)),
				('live_url', models.URLField(blank=True)),
				('code_url', models.URLField(blank=True)),
				('thumbnail', models.ImageField(upload_to='projects/')),
				('is_featured', models.BooleanField(default=False)),
				('score', models.IntegerField(blank=True, null=True)),
				('features', models.JSONField(default=list, help_text='List of key features')),
				('challenges', models.TextField(blank=True, help_text='Technical challenges overcome')),
				('lessons', models.TextField(blank=True, help_text='Key lessons learned')),
				('video_url', models.URLField(blank=True)),
				('architecture_diagram', models.ImageField(blank=True, upload_to='architecture/')),
			],
		),
		migrations.CreateModel(
			name='Gallery',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=200)),
				('description', models.TextField(blank=True)),
				('order', models.PositiveIntegerField(default=0)),
				('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='projects.project')),
			],
			options={
				'verbose_name_plural': 'Galleries',
				'ordering': ['order'],
			},
		),
		migrations.CreateModel(
			name='GalleryImage',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('image', models.ImageField(upload_to='galleries/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
				('caption', models.CharField(blank=True, max_length=200)),
				('order', models.PositiveIntegerField(default=0)),
				('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.gallery')),
			],
			options={
				'ordering': ['order'],
				'indexes': [models.Index(fields=['gallery', 'order'], name='projects_ga_gallery_348ef2_idx')],
			},
		),
	]
