# Generated by Django 5.0.13 on 2025-03-14 15:39

import django.core.validators
from django.db import migrations, models

import projects.storage


class Migration(migrations.Migration):

	dependencies = [
		('projects', '0003_auto_20250312_1755'),
	]

	operations = [
		migrations.AddField(
			model_name='project',
			name='demo_commands',
			field=models.JSONField(blank=True, help_text='JSON commands for interactive terminal', null=True),
		),
		migrations.AddField(
			model_name='project',
			name='demo_files_path',
			field=models.CharField(blank=True, help_text='Path to demo files', max_length=200),
		),
		migrations.AddField(
			model_name='project',
			name='has_interactive_demo',
			field=models.BooleanField(default=False),
		),
		migrations.AlterField(
			model_name='gallery',
			name='name',
			field=models.CharField(default='Unnamed Gallery', max_length=200),
		),
		migrations.AlterField(
			model_name='galleryimage',
			name='image',
			field=models.ImageField(storage=projects.storage.CustomS3Storage(), upload_to='galleries/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
		),
		migrations.AlterField(
			model_name='project',
			name='architecture_diagram',
			field=models.TextField(blank=True, help_text='\n\t\tSupported formats:\n\t\t- Mermaid.js (preferred)\n\t\t- PlantUML\n\t\t- ASCII diagram\n\t\t- SVG XML\n\t\t', null=True),
		),
		migrations.AlterField(
			model_name='project',
			name='diagram_type',
			field=models.CharField(choices=[('MERMAID', 'Mermaid.js'), ('PLANTUML', 'PlantUML'), ('ASCII', 'ASCII Art'), ('SVG', 'SVG XML'), ('CUSTOM', 'Custom Format')], default='MERMAID', help_text='Format of the architecture diagram', max_length=10),
		),
		migrations.AlterField(
			model_name='project',
			name='thumbnail',
			field=models.ImageField(blank=True, help_text='Thumbnail image for project', null=True, storage=projects.storage.CustomS3Storage(), upload_to='projects/'),
		),
	]
