# Generated by Django 5.0.13 on 2025-03-18 20:08

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_code_snippets_project_code_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Alternative URL for thumbnail', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='architecture_diagram',
            field=models.TextField(blank=True, help_text='Architecture diagram code (for Mermaid/Flowchart) or image URL', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='Challenges faced during development', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_snippets',
            field=models.JSONField(blank=True, help_text='List of code snippets', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_steps',
            field=models.JSONField(blank=True, help_text='List of steps to run the code', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_url',
            field=models.URLField(blank=True, help_text='Link to source code', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_commands',
            field=models.JSONField(blank=True, help_text='Demo commands for interactive terminal', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='diagram_type',
            field=models.CharField(choices=[('mermaid', 'Mermaid.js'), ('flowchart', 'Flowchart.js'), ('custom', 'Custom SVG/Image')], default='mermaid', help_text='Type of architecture diagram', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.JSONField(blank=True, help_text='List of project features with completion percentages', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_interactive_demo',
            field=models.BooleanField(default=False, help_text='Whether this project has an interactive terminal demo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lessons',
            field=models.TextField(blank=True, help_text='Lessons learned from the project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Link to live demo', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='readme',
            field=models.TextField(blank=True, help_text='Full README content in Markdown format', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='score',
            field=models.IntegerField(default=0, help_text='Project score (0-125)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(125)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
		migrations.AlterField(
			model_name='project',
			name='tech_stack',
			field=models.JSONField(blank=True, null=True, help_text='List of technologies used in the project'),
		),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='URL to project thumbnail image', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to project video demonstration', null=True),
        ),
    ]
