# Generated by Django 5.2.8 on 2025-11-20 15:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_convert_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='galleries/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Project thumbnail image', null=True, upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text="Company name (e.g., 'Qynapse Healthcare')", max_length=255)),
                ('role', models.CharField(help_text='Role/position title', max_length=255)),
                ('subtitle', models.CharField(help_text='Role description/subtitle for hero section', max_length=500)),
                ('slug', models.SlugField(help_text='URL slug (auto-generated from company)', max_length=100, unique=True)),
                ('start_date', models.DateField(help_text='Internship start date')),
                ('end_date', models.DateField(blank=True, help_text='Internship end date (null if current)', null=True)),
                ('overview', models.TextField(help_text='Overview paragraph describing the experience')),
                ('stats', models.JSONField(default=list, help_text='Hero stats as JSON array: [{"value": "10,000+", "label": "Lines of Code", "color": "blue"}, ...]')),
                ('technologies', models.JSONField(default=list, help_text='Technologies array: [{"name": "FastAPI", "icon": "⚡", "category": "backend", "level": 5}, ...]')),
                ('impact_metrics', models.JSONField(default=list, help_text='Impact metrics: [{"value": "10000", "label": "Lines of Code", "description": "...", "icon": "💻"}, ...]')),
                ('architecture_description', models.TextField(blank=True, help_text='Description of the architecture/technical approach', null=True)),
                ('architecture_diagram', models.TextField(blank=True, help_text='Mermaid diagram code or SVG for Zero Trust architecture', null=True)),
                ('code_samples', models.JSONField(default=list, help_text='Code samples: [{"title": "...", "description": "...", "code": "...", "language": "python"}, ...]')),
                ('documentation', models.JSONField(default=list, help_text='Documentation items: [{"title": "...", "description": "...", "category": "architecture", "icon": "📄"}, ...]')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this internship should be displayed on the site')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-start_date'],
                'indexes': [models.Index(fields=['slug'], name='internship_slug_idx'), models.Index(fields=['is_active', 'order'], name='internship_active_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternshipProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=255)),
                ('slug', models.SlugField(help_text='URL slug for project detail page', max_length=100)),
                ('description', models.TextField(help_text='Short description for project card')),
                ('thumbnail', models.ImageField(blank=True, help_text='Project thumbnail (architecture diagram or screenshot)', null=True, upload_to='internship/projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg'])])),
                ('thumbnail_url', models.URLField(blank=True, help_text='Alternative URL for thumbnail', null=True)),
                ('overview', models.TextField(blank=True, help_text='Detailed overview for project detail page', null=True)),
                ('role_description', models.TextField(blank=True, help_text='Your specific role and contributions', null=True)),
                ('tech_stack', models.JSONField(default=list, help_text='Technologies used: ["FastAPI", "PostgreSQL", "Docker", ...]')),
                ('stats', models.JSONField(default=dict, help_text='Project stats: {"ownership": "80%", "linesOfCode": "10,000+", "adoption": "Company-wide"}')),
                ('badges', models.JSONField(default=list, help_text='Badges: [{"text": "Primary Project", "variant": "primary"}, ...]')),
                ('architecture_description', models.TextField(blank=True, help_text='Architecture explanation for detail page', null=True)),
                ('architecture_diagrams', models.JSONField(default=list, help_text='Architecture diagrams: [{"title": "...", "diagram": "mermaid code or URL", "description": "..."}, ...]')),
                ('key_features', models.JSONField(default=list, help_text='Key features: [{"title": "...", "description": "...", "icon": "🔐"}, ...]')),
                ('code_snippets', models.JSONField(default=list, help_text='Code examples: [{"title": "...", "code": "...", "language": "python", "description": "..."}, ...]')),
                ('impact_metrics', models.JSONField(default=list, help_text='Impact metrics specific to this project')),
                ('related_documentation', models.JSONField(default=list, help_text='Related docs: [{"title": "...", "description": "...", "category": "...", "icon": "..."}, ...]')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within internship')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this project prominently')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.internship')),
            ],
            options={
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['internship', 'slug'], name='int_project_slug_idx'), models.Index(fields=['internship', 'order'], name='int_project_order_idx')],
                'unique_together': {('internship', 'slug')},
            },
        ),
    ]
