# Generated by Django 5.2.8 on 2025-11-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_galleryimage_image_alter_project_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='badges',
            field=models.JSONField(blank=True, help_text='Badges: [{"text": "Zero Trust", "color": "blue"}, ...]', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, help_text='Company name (for internship projects)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Project end date (for internship projects)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_metrics',
            field=models.JSONField(blank=True, help_text='Impact metrics: {"security_vulnerabilities_prevented": "15+", ...}', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('school', 'School Project'), ('internship', 'Internship Project')], default='school', help_text='Type of project: school or internship', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='Role/position (for internship projects)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='role_description',
            field=models.TextField(blank=True, help_text='Your specific role and contributions (for internship projects)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Project start date (for internship projects)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stats',
            field=models.JSONField(blank=True, help_text='Project stats: {"coverage": "85%", "endpoints": "15+", ...}', null=True),
        ),
    ]
