# F1-06 — Schema v2, part 1: additive Project/Experience changes (rework/v2).
#
# Field map: docs/designs/2026-10-05-schema-v2-field-map.md (§2.1, §2.2, §3.5)
#
# WHAT THIS DOES (purely additive + column alters — applies cleanly to
# pre-ETL data, map §3.5):
#   - CreateModel Experience (thin grouping table; content rescued by F1-07)
#   - Project: new columns (architecture_description, architecture_diagrams,
#     related_documentation, order, created_at/updated_at, experience FK)
#   - Project: altered columns (canonical JSON policy — NOT NULL + list
#     defaults; project_type choices + personal with default REMOVED; score
#     nullable; has_interactive_demo RENAMED to has_demo)
#   - Indexes: drop redundant project_slug_idx; add project_type_order_idx +
#     project_demo_idx (partial, has_demo=True)
#
# WHY SEPARATE FROM THE DROP (0012): the deprecated Internship/InternshipProject
# tables AND the old Project columns (architecture_diagram/diagram_type/
# company/role/start_date/end_date) are rescue SOURCES — the ETL (F1-07) runs
# BETWEEN 0011 and 0012 (flip order: reconcile → 0011 → etl_v2 → 0012 → contact
# delta, map §5.10). The DB-level project_type CheckConstraint is likewise
# post-ETL (0012, map §5.6). Column drops live in 0012 for the same reason.
#
# FIELD FIDELITY NOTE: operation bodies below were generated by
# `makemigrations` from the v2 models (verbatim fidelity), then hand-adjusted
# in exactly three ways, each field-map-mandated:
#   1. has_interactive_demo → has_demo is RenameField (autodetector proposed
#      Remove+Add, which would reset demo flags to False — data loss).
#   2. created_at/updated_at AddFields carry a one-off default (timezone.now)
#      for the 12 existing rows — auto_now_add alone cannot backfill.
#   3. Column drops + constraint + model deletes are deferred to 0012
#      (post-ETL, map §5.6/§5.10).
#
# REVERSIBILITY: fully reversible by construction — every operation's reverse
# is exact (RenameField back, AlterField back to the 0010 state, AddField/
# AddIndex/CreateModel reverses). Verified against the G3-restored DB (see
# .github/agent-reports/senior-dev/f1-06-models-v2.md).
#
# NULL-SAFETY OF THE JSON ALTERS: the NOT NULL + list-default alterations are
# safe on the restored dump — its 12 Project rows hold populated (non-NULL)
# values in every affected JSON column (verified during the F1-05 ground-truth
# read; the serializers' `or []` guards were defensive, not load-bearing).
# etl_v2 (F1-07) remains the sweeper of record for any NULL that appears in
# the flip window (map §3.2).

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_ghost_reconciliation'),
    ]

    operations = [
        # ── Experience: the thin grouping table (map §2.2) ──────────────────
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text="Company name (e.g. 'Qynapse')", max_length=255)),
                ('role', models.CharField(help_text='Role/position title', max_length=255)),
                ('subtitle', models.CharField(help_text='Hero one-liner for the experience section', max_length=500)),
                ('slug', models.SlugField(help_text='URL slug (keys the F5-04 redirects)', max_length=100, unique=True)),
                ('start_date', models.DateField(help_text='Start date')),
                ('end_date', models.DateField(blank=True, help_text='End date (null = current)', null=True)),
                ('overview', models.TextField(help_text='Long-form overview of the experience')),
                ('stats', models.JSONField(blank=True, default=list, help_text='Canonical: [{"label": str, "value": str}]')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='Canonical: [{"name": str, "category"?: str}]')),
                ('impact_metrics', models.JSONField(blank=True, default=list, help_text='Canonical: [{"label": str, "value": str, "description"?: str}]')),
                ('architecture_description', models.TextField(blank=True, help_text='Architecture prose (e.g. the ZTA layers)', null=True)),
                ('architecture_diagrams', models.JSONField(blank=True, default=list, help_text='Canonical: [{"title": str, "type": str, "content": str, "description"?: str}]')),
                ('code_samples', models.JSONField(blank=True, default=list, help_text='Canonical: [{"title": str, "description"?: str, "language"?: str, "code": str, "category"?: str}]')),
                ('documentation', models.JSONField(blank=True, default=list, help_text='Canonical: [{"title": str, "description"?: str, "category"?: str}]')),
                ('is_active', models.BooleanField(default=True, help_text='Display toggle')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['is_active', 'order'], name='experience_active_order_idx'),
        ),

        # ── Project: new columns (map §2.1 rescued/NEW fields) ──────────────
        migrations.AddField(
            model_name='project',
            name='architecture_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='architecture_diagrams',
            field=models.JSONField(blank=True, default=list, help_text='Canonical: [{"title": str, "type": str, "content": str, "description"?: str}] — type in mermaid|flowchart|custom'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_documentation',
            field=models.JSONField(blank=True, default=list, help_text='Canonical: [{"title": str, "description"?: str, "category"?: str}]'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ledger ordering (lower first)'),
        ),
        # One-off default backfills the 12 existing rows (auto_now_add alone
        # cannot add a NOT NULL column to a non-empty table).
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='experience',
            field=models.ForeignKey(blank=True, help_text='Linked experience (internship projects); PROTECT prevents orphaning', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.experience'),
        ),

        # ── Project: renames and column changes (map §2.1 TRANSFORM) ────────
        migrations.RenameField(
            model_name='project',
            old_name='has_interactive_demo',
            new_name='has_demo',
        ),
        migrations.AlterField(
            model_name='project',
            name='has_demo',
            field=models.BooleanField(default=False, help_text='Whether this project has an interactive terminal demo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('school', 'School Project'), ('internship', 'Internship Project'), ('personal', 'Personal Project')], help_text='Type of project: school, internship or personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='score',
            field=models.IntegerField(blank=True, default=None, help_text='School-context score (0-125); null when not applicable (internship/personal)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(125)]),
        ),
        # Canonical JSON policy (map §3.2): NOT NULL + list defaults
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, help_text='Canonical: [{"name": str, "category"?: str}]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Canonical: [str] — plain feature strings'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_commands',
            field=models.JSONField(blank=True, default=list, help_text='Canonical: [{"label": str, "command": str}]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_steps',
            field=models.JSONField(blank=True, default=list, help_text='Canonical: [str] — ordered steps'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_snippets',
            field=models.JSONField(blank=True, default=list, help_text='Canonical: [{"title"?: str, "description"?: str, "language"?: str, "code": str}]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stats',
            field=models.JSONField(blank=True, default=list, help_text='Canonical: [{"label": str, "value": str}]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='badges',
            field=models.JSONField(blank=True, default=list, help_text='Canonical: [{"text": str}] — color/variant keys are gone (brief §2.5)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='impact_metrics',
            field=models.JSONField(blank=True, default=list, help_text='Canonical: [{"label": str, "value": str, "description"?: str}]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_files_path',
            field=models.CharField(blank=True, help_text='R2 key of the demo zip (under project-files/)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lessons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='readme',
            field=models.TextField(blank=True, help_text='Single long-form body (Markdown)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='role_description',
            field=models.TextField(blank=True, help_text='Your specific role and contributions on this project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Project thumbnail image (required when featured)', null=True, upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='External thumbnail URL (escape hatch)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),

        # ── Indexes + Meta (map §3.5) ────────────────────────────────────────
        migrations.RemoveIndex(
            model_name='project',
            name='project_slug_idx',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type', 'order'], name='project_type_order_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(condition=models.Q(('has_demo', True)), fields=['has_demo'], name='project_demo_idx'),
        ),
    ]
