# F1-10 — Admin-facing help_text updates (rework/v2).
#
# Surfaces the two F1-07 ETL flags at the model level so the admin shows them
# on the form: related_documentation placeholder warning + demo_files_path
# manifest pointer. Schema-only metadata change (help_text) — no data impact.
# (Generated by the local venv's Django 5.2.8 — operations are version-agnostic
# AlterField help_text changes; requirements pin applies to the Docker image.)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_drop_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_files_path',
            field=models.CharField(blank=True, help_text='R2 key of the demo zip (under project-files/) — verified keys: see demo_files_manifest in fixtures/stale_internship_content.json (currently only project-files/minishell.zip; Phase 4 uploads more)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='related_documentation',
            field=models.JSONField(blank=True, default=list, help_text='Canonical: [{"title": str, "description"?: str, "category"?: str}] — NOTE: the 3 internship rows currently hold rescued placeholder content ("...") pending real documentation (F1-07 flag) — replace in admin'),
        ),
    ]
