name: Keep Services Alive
on:
  schedule:
    # Run every 20 minutes
    - cron: '*/20 * * * *'
  workflow_dispatch:

# No permissions needed - workflow only makes external HTTP requests
permissions: {}

jobs:
  ping-services:
    runs-on: ubuntu-latest
    permissions: {}  # No repository access needed
    steps:
      - name: Ping backend service
        run: curl -s -o /dev/null -w "%{http_code}" https://api.aouichou.me/healthz || echo "Backend ping failed"
      
      - name: Ping terminal service
        run: curl -s -o /dev/null -w "%{http_code}" https://portfolio-terminal-4t9w.onrender.com/healthz || echo "Terminal ping failed"
      
      - name: Ping frontend
        run: curl -s -o /dev/null -w "%{http_code}" https://aouichou.me || echo "Frontend ping failed"