# .github/workflows/monitor.yml

name: Terminal Monitoring
on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  check-terminal:
    runs-on: ubuntu-latest
    steps:
      - name: Install websocat
        run: |
          wget -q https://github.com/vi/websocat/releases/download/v1.11.0/websocat.x86_64-unknown-linux-musl
          chmod +x websocat.x86_64-unknown-linux-musl
          sudo mv websocat.x86_64-unknown-linux-musl /usr/local/bin/websocat
      
      - name: Test API Health
        run: |
          response=$(curl -s https://api.aouichou.me/api/health/ || echo "Connection failed")
          echo "API response: $response"
          
          if echo "$response" | grep -q "healthy"; then
            echo "API service is healthy! 🟢"
          else
            echo "API service check failed 🔴" >> $GITHUB_STEP_SUMMARY
            echo "Response: $response" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Test Terminal Service Health
        run: |
          response=$(curl -s https://portfolio-terminal-4t9w.onrender.com/healthz || echo "Connection failed")
          echo "Terminal response: $response"
          
          if echo "$response" | grep -q "healthy"; then
            echo "Terminal service is healthy! 🟢"
          else
            echo "Terminal service check failed 🔴" >> $GITHUB_STEP_SUMMARY
            echo "Response: $response" >> $GITHUB_STEP_SUMMARY
          fi